import Link from "next/link";

export const metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <h1>Home</h1>
      <Link href="/about">Check About Page</Link>
    </>
  );
}
